### ISSUE TITLE
Suggestion to add FakeJSON as one of JSON tools

### ISSUE THREAD

**Issue by pelmenept** [FrontendMasters/front-end-handbook-2018#17]
Hi!
We've built a test data generator service, which responds to HTTP requests and helps with mocking data for front end projects. Any type of data.

It would be great if you would consider adding it as one of the available JSON tools in the "Font End Handbook 2018".
https://fakejson.com
thanks

**Comment by codylindley** [comment]
Sure. I like it. Can you make a PR?
