### ISSUE TITLE
Download link doesn't work 

### ISSUE THREAD

**Issue by lukaszgodula** [FrontendMasters/front-end-handbook-2018#6]
There is still no possibility to download the book. Link is not working.

**Comment by danikkks** [comment]
pdf and epub versions - 

[front-end-handbook.pdf](https://github.com/FrontendMasters/front-end-handbook-2018/files/1649658/front-end-handbook.pdf)

**Comment by danikkks** [comment]
[front-end-handbook.epub.zip](https://github.com/FrontendMasters/front-end-handbook-2018/files/1649662/front-end-handbook.epub.zip)

**Comment by danikkks** [comment]
but books logo is still from 2017

**Comment by lukaszgodula** [comment]
Just askin: any plans for mobi?

**Comment by danikkks** [comment]
[front-end-handbook.mobi.zip](https://github.com/FrontendMasters/front-end-handbook-2018/files/1651715/front-end-handbook.mobi.zip)
