### ISSUE TITLE
Is front-end-handbook-2019 ready ?

### ISSUE THREAD

**Issue by pereiraryan** [FrontendMasters/front-end-handbook-2018#73]
I cant wait for the 2019 edition of  front-end-handbook-2019. is there any release date for the same?

**Comment by codylindley** [comment]
Hoping for mid-Feb.

**Comment by sarates** [comment]
Would be nice if update will include best development practices (git, js, scss, linters, react, etc), not only links to learning resources.

**Comment by rewaant** [comment]
Eagerly waiting. 2018 one helped me so much. Can't wait to read the 2019. Hats off for your efforts @codylindley .

**Comment by skayablars** [comment]
Looking forward :)

**Comment by jesraygarciano** [comment]
I'm really excited.

**Comment by junibrosas** [comment]
While this is not out yet, check out the [web developer roadmap 2019](https://github.com/kamranahmedse/developer-roadmap).

**Comment by DoctaCloak** [comment]
How much longer on this @codylindley 🤔

**Comment by yusjs** [comment]
Looking forward to read the new version

**Comment by codylindley** [comment]
The 2019 version is done. I'll let @1Marc discuss its release. As a teaser, we are potentially seeing this content expanding in the future into a set of individual guides. And for those who liked the roadmap mentioned above have a look at what we are playing with as a roadmap for the future. https://sketchboard.me/dBs5rTm2QTDP#/ (as requested the goal is to dive deeper than the handbook into each of these categories).

**Comment by 1Marc** [comment]
We'll be releasing the 2019 handbook as part of our spring promotion in April! (for free and in the open again)

And yes... as @codylindley mentioned, we're planning to expand the scope on this project A LOT throughout 2019 and beyond. 🚀

**Comment by aech12** [comment]
There was so much exciting new stuff to learn that I thought you wouldn't do it in 2019, because it'd would be a ton of work

**Comment by hrahimi270** [comment]
@1Marc it's April now (:

**Comment by 1Marc** [comment]
@hrahimi270 April isn't over yet! It will be out in the next week or so.

**Comment by RajrupBorooah** [comment]
Yes, it's available now. Here's the link: https://frontendmasters.com/books/front-end-handbook/2019/
